### ISSUE TITLE
没看懂使用说明

### ISSUE THREAD

**Issue by henghengkan** [spxvszero/QueueDanmu#1]
作者你这个上面写的配置爱ak，as，id都在哪啊，还有什么是注释掉

**Comment by spxvszero** [comment]
需要在 bilibili 申请开发者账号, 通过审核后即可获得 ak 和 as
AppID 是在 饭贩 上创建的, 现在 b站 已经将其更名为 幻星互动 https://play-live.bilibili.com/

**Comment by henghengkan** [comment]
bilibili还有开发者账号，普通人的账号还用不了这个工具吗
ID是不是就是身份码

**Comment by henghengkan** [comment]
> 需要在 bilibili 申请开发者账号, 通过审核后即可获得 ak 和 as AppID 是在 饭贩 上创建的, 现在 b站 已经将其更名为 幻星互动 https://play-live.bilibili.com/

https://open-live.bilibili.com/open-manage 是这个链接申请是吧，作者大大，一定要申请吗

**Comment by spxvszero** [comment]
> bilibili还有开发者账号，普通人的账号还用不了这个工具吗

是的, 这个工具是做给主播用的, 所以基于当时的开发规范写的, 如果你要抓取弹幕的话, 可以参考别的仓库

> ID是不是就是身份码

AppID 是创建的项目的身份码, 不一样的, 直播的身份码在程序打开之后, 会有页面需要填写的

> [https://open-live.bilibili.com/open-manage是这个链接申请是吧，作者大大，一定要申请吗](https://open-live.bilibili.com/open-manage%E6%98%AF%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E7%94%B3%E8%AF%B7%E6%98%AF%E5%90%A7%EF%BC%8C%E4%BD%9C%E8%80%85%E5%A4%A7%E5%A4%A7%EF%BC%8C%E4%B8%80%E5%AE%9A%E8%A6%81%E7%94%B3%E8%AF%B7%E5%90%97)

这个取决于你的目的, 如果你是想开发这样一款工具在 b站 开放平台上的话, 那就需要, 如果是用于抓取弹幕等个人需求的话, 还
是参考其他项目, 流程会简单很多

**Comment by henghengkan** [comment]
> 这个取决于你的目的, 如果你是想开发这样一款工具在 b站 开放平台上的话, 那就需要, 如果是用于抓取弹幕等个人需求的话, 还 是参考其他项目, 流程会简单很多

啊？我只是想使用你这个工具用来获取排队信息👀

**Comment by henghengkan** [comment]
我使用这个项目是不是还要去弄fyne项目啊作者

**Comment by henghengkan** [comment]
> 需要在 bilibili 申请开发者账号, 通过审核后即可获得 ak 和 as AppID 是在 饭贩 上创建的, 现在 b站 已经将其更名为 幻星互动 https://play-live.bilibili.com/

作者，那个什么注释掉你还没给我解释呢，看不懂(((φ(◎ロ◎;)φ)))

**Comment by henghengkan** [comment]
啊！作者，说了这么多，我是不是直接去你的饭饭上https://play-live.bilibili.com/details/1683719959529 下载就可以直接用了 T - T

**Comment by spxvszero** [comment]
> 啊！作者，说了这么多，我是不是直接去你的饭饭上https://play-live.bilibili.com/details/1683719959529 下载就可以直接用了 T - T

如果你只是想用而不是二次开发，那当然直接下载是最快的
